### ISSUE TITLE
Missing RepeatFinder tool 

### ISSUE THREAD

**Issue by gunjanhariani** [OSU-SRLab/MANTIS#14]
Hi Russell,

I cloned the master repository for MANTIS today but could not locate the RepeatFinder tool. Could you please help me with that?

Thanks!
Gunjan

**Comment by rbonneville** [comment]
The source code is in the tools directory. cd into it and run 'make'. GCC is required to compile it.

**Comment by gunjanhariani** [comment]
Thank you!
