### ISSUE TITLE
MANTIS on WGS samples

### ISSUE THREAD

**Issue by Rashesh7** [OSU-SRLab/MANTIS#25]
Hi,

I am testing MANTIS on a few samples and was wondering if you have tested it on WGS samples?
In the Readme you have recommended thresholds for Whole-Exome usage, but do you have some recommendations for whole-genome usage?

Any help and support is appreciated.

Thank you.

**Comment by messersc** [comment]
Hi @rbonneville,

we do have a similar question. We have some tumor/normal paired WGS data with median coverages of ~70-80x. Which other quality statistics do you need or is this sufficient to recommend parameters for MANTIS?

Thanks,
Clemens

**Comment by rbonneville** [comment]
Hi @messersc, do you have any quality statistics, for instance %Q30?

**Comment by messersc** [comment]
Hi @rbonneville, the runs look very good in general, the %Q30 is > 95 % for all libraries (this is paired-end, 151 bp data).

**Comment by rbonneville** [comment]
Given the high %Q30 and your median coverages, I would recommend first trying whole exome parameters.
