### ISSUE TITLE
Loci in MANTIS output are sorted alphabetically

### ISSUE THREAD

**Issue by mdyckmanns** [OSU-SRLab/MANTIS#32]
If sorting the loci, at least the positions within each chromosome block should be sorted (alpha)numerically instead of alphabetically. One could alternatively just take the order of loci from the input bed file.

Thanks and best regards
Malte

**Comment by rbonneville** [comment]
Have this working for Python 2.x, pending testing for Python 3.x.

**Comment by rbonneville** [comment]
Merged in #36
