### ISSUE TITLE
score range

### ISSUE THREAD

**Issue by twelvesummer** [OSU-SRLab/MANTIS#35]
hello,I have read this script from a paper named "Performance evaluation for rapid detection of pan-cancer
microsatellite instability with MANTIS" which writed "Once the scores for each locus are assigned,the average of all the locus instability scores is calculated,to provide a single numerical value representing the
average aggregate instability present in the sample. Scores reported range from 0.0 (entirely stable) to 2.0 (entirelyunstable).". **However,I find mantis.py that the default value isn't the same,which one above?** 
Parameter(key='dif_threshold', default=0.4),
Parameter(key='euc_threshold', default=0.187),
Parameter(key='cos_threshold', default=0.07),

**Comment by rbonneville** [comment]
Hello @twelvesummer ,

These default values are for thresholds to classify a sample as MSI-H (microsatellite instability-high). Although the code provides three distance metrics for comparing microsatellite length distributions, we recommend the DIF metric (default threshold 0.4).

With this recommended metric and default settings, a tumor's (versus its matched normal) MSI score will fall within [0.0, 2.0], and tumors with score >=0.4 are called MSI-H.
