### ISSUE TITLE
MANTIS on Mouse samples

### ISSUE THREAD

**Issue by Rashesh7** [OSU-SRLab/MANTIS#38]
Hi, 

I was wondering if you have tested MANTIS on mouse samples?
Also I was thinking since Mantis uses the MS regions generated by RepeatFinder and gets the distribution of the repeats at those locations in the input tumor and normal samples, it should behave similarly for Mouse also, right?

Please let me know if I am assuming something incorrectly.
Your support and suggestions are much appreciated. 

Thank you!

**Comment by rbonneville** [comment]
Hello Rashesh7,

We have not tested MANTIS on mouse samples, however MANTIS should in theory work for mouse data as well as human. Note that RepeatFinder, given a fasta file, will identify all microsatellites in a genome (according to MANTIS's definition of a microsatellite). The resulting BED file should further be filtered to remove microsatellites outside of your capture region.

**Comment by Rashesh7** [comment]
Hi @rbonneville ,
Yeah, that is what I was thinking.  Thank you for your quick reply. 

Also, do you think the threshold of 0.4 should still be fine to determine the instability?
