### ISSUE TITLE
Issue in runni

### ISSUE THREAD

**Issue by YuvaraniThambidurai** [OSU-SRLab/MANTIS#47]
Hi
   The Bed file generated from RepeatFinder is of length 3109671 lines. I tried to use this BED file for MANTIS but after running couple of hours, I often receive the message as Broken pipe. In all the condition I have used 3 threads as per your advice. Could u please help me in resolving this?

**Comment by rbonneville** [comment]
RepeatFinder finds all putative microsatellite regions in an entire genome. This BED file must be filtered with your desired capture region, for example:

`bedtools intersect -a microsatellites.bed -b regions.bed -wa > microsatellites_filtered.bed`
