### ISSUE TITLE
interpreter mismatch

### ISSUE THREAD

**Issue by lozybean** [OSU-SRLab/MANTIS#52]
it causes bug when is in the multi-interpreter environment;

For example, there are two interpreters: `python3` and `python`, but only `python3`  install `numpy`, `calculate_instability.py` will crash with exception: `no module named numpy`.

**Comment by lozybean** [comment]
plz check this PR to fix it: https://github.com/OSU-SRLab/MANTIS/pull/53

**Comment by rbonneville** [comment]
Merged. Thank you!
