### ISSUE TITLE
About MS loci BED file used in MANTIS

### ISSUE THREAD

**Issue by Leon352** [OSU-SRLab/MANTIS#55]
Hi,
I’m not familiar with MANTIS.When running MANTIS on WGS data,I don’t know how to generate the proper MS loci BED file.Because I use Repeatfinder to generate the bed file including MS loci through entire genome. As the answer in: 
https://github.com/OSU-SRLab/MANTIS/issues/40#issuecomment-425133436
I shouldn’t use the MS loci BED file through entire genome.But I don’t have capture regions(my data is WGS data) or interested region.How can I filter my MS loci bed?
I want to know if these two approaches work:
1)select protein coding gene region
2)select MS loci that MANTIS paper uses for TCGA data
Are there any approaches for WGS data?
Thanks!

**Comment by rbonneville** [comment]
Hello Leon352,

If you are interested in MSI vs. MSS calls, I would recommend just using the loci from the MANTIS paper (attached, coordinates in hg19), and in addition using the suggested quality thresholds for whole exome data (https://github.com/OSU-SRLab/MANTIS#whole-exome-usage). Please let us know if you have any additional questions or encounter difficulties.

[wes_2539_hg19.zip](https://github.com/OSU-SRLab/MANTIS/files/3922971/wes_2539_hg19.zip)
