### ISSUE TITLE
Is it possible that using MANTIS to analyze RNAseq data?

### ISSUE THREAD

**Issue by hqu-arcus** [OSU-SRLab/MANTIS#56]
Hello,

I understand that MANTIS was designed to analyze DNA-based sequencing data, but I'm wondering if RNAseq bam files could be used as input data. Or is there any recommended software for estimating RNAseq MSI status.

Thanks!

**Comment by rbonneville** [comment]
Hello,

We have not tested or benchmarked MANTIS on RNA data, though in principle it may be possible provided that only microsatellites in expressed coding sequences are utilized. However this would likely be difficult, for instance expression of alleles containing neoantigens secondary to MSI may be selected against (just speculation, no data for or against this).

Perhaps PreMSIm (https://www.sciencedirect.com/science/article/pii/S2001037019305446) may be useful, which utilizes a gene expression profile associated with MSI.

**Comment by hqu-arcus** [comment]
Thank you so much for your detailed answer!
